# ********RoostGPT********

# Test generated by RoostGPT for test products using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /AddRecurringTransfers_post for http method type POST 
# RoostTestHash=b9ae237532
# 
# 

# ********RoostGPT********
Feature: Add Recurring Transfers API Tests

  Background:
    * def baseURL = karate.properties['BANKASSIST_CORE_BANKING_SPECIFICATION_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Test Add Recurring Transfers with valid inputs
    Given path '/AddRecurringTransfers'
    And request
      """
      {
        "customerId": <customerId>,
        "amount": <amount>,
        "sourceAccountId": '<sourceAccountId>',
        "targetAccountId": '<targetAccountId>',
        "currency": '<currency>',
        "status": '<status>',
        "scheduledDate": <scheduledDate>,
        "recurringOptions": {
          "amountType": '<amountType>',
          "frequency": {
            "iterate": '<iterate>',
            "duration": {
              "numberOfTransfers": <numberOfTransfers>
            }
          }
        }
      }
      """
    And headers { koreUserId: '<koreUserId>', botId: '<botId>', userCode: '<userCode>', accountId: '<accountId>' }
    When method POST
    Then status 200

  Examples:
    | customerId | amount | sourceAccountId | targetAccountId | currency | status   | scheduledDate | amountType | iterate | numberOfTransfers | koreUserId | botId | userCode | accountId |
    | 1045304    | 39     | '1042347'       | '1043699'       | 'USD'    | 'Pending'| 1616544000000 | 'Fixed'   | 'Weekly'| 3                 | 'user1'    | 'bot1'| 'code1'  | 'acc1'    |

  Scenario: Test Add Recurring Transfers with missing authorization
    Given path '/AddRecurringTransfers'
    And request
      """
      {
        "customerId": 1045304,
        "amount": 39,
        "sourceAccountId": "1042347",
        "targetAccountId": "1043699",
        "currency": "USD",
        "status": "Pending",
        "scheduledDate": 1616544000000,
        "recurringOptions": {
          "amountType": "Fixed",
          "frequency": {
            "iterate": "Weekly",
            "duration": {
              "numberOfTransfers": 3
            }
          }
        }
      }
      """
    And headers { koreUserId: 'user1', botId: 'bot1', userCode: 'code1', accountId: 'acc1' }
    When method POST
    Then status 401
    And match response.err.message == '#string'

  Scenario: Test Add Recurring Transfers with invalid endpoint
    Given path '/InvalidEndpoint'
    And request
      """
      {
        "customerId": 1045304,
        "amount": 39,
        "sourceAccountId": "1042347",
        "targetAccountId": "1043699",
        "currency": "USD",
        "status": "Pending",
        "scheduledDate": 1616544000000,
        "recurringOptions": {
          "amountType": "Fixed",
          "frequency": {
            "iterate": "Weekly",
            "duration": {
              "numberOfTransfers": 3
            }
          }
        }
      }
      """
    And headers { koreUserId: 'user1', botId: 'bot1', userCode: 'code1', accountId: 'acc1' }
    When method POST
    Then status 404
    And match response.err.message == '#string'
