# ********RoostGPT********

# Test generated by RoostGPT for test products using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /ccPay_post for http method type POST 
# RoostTestHash=c6fa681866
# 
# 

# ********RoostGPT********
Feature: Credit Card Payment API Tests

  Background:
    * def baseURL = karate.properties['BANKASSIST_CORE_BANKING_SPECIFICATION_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN'] || karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Test Credit Card Payment with Valid Inputs
    Given path '/ccPay'
    And request { "customerId": <customerId>, "amount": <amount>, "currency": '<currency>', "sourceAccountId": '<sourceAccountId>', "targetAccountId": '<targetAccountId>', "transactionType": <transactionType>, "dueDate": '<dueDate>' }
    And header botId = '<botId>'
    And header accountId = '<accountId>'
    When method POST
    Then status 200
    And match response == {}

    Examples:
      | customerId | amount | currency | sourceAccountId | targetAccountId | transactionType | dueDate                      | botId   | accountId |
      | 1045304    | 300    | 'USD'    | '1045302'       | '1042224'       | 1053            | '2021-03-24T00:00:00.000+0000' | 'bot1'  | 'acc1'    |

  Scenario: Test Unauthorized Access
    Given path '/ccPay'
    And request { "customerId": 1045304, "amount": 300, "currency": 'USD', "sourceAccountId": '1045302', "targetAccountId": '1042224', "transactionType": 1053, "dueDate": '2021-03-24T00:00:00.000+0000' }
    And header botId = 'bot1'
    And header accountId = 'acc1'
    * configure headers = { Accept: 'application/json' } # No Authorization header
    When method POST
    Then status 401
    And match response.err.message == '#string'

  Scenario: Test Not Found Error
    Given path '/ccPay'
    And request { "customerId": 9999999, "amount": 300, "currency": 'USD', "sourceAccountId": '9999999', "targetAccountId": '9999999', "transactionType": 1053, "dueDate": '2021-03-24T00:00:00.000+0000' }
    And header botId = 'bot1'
    And header accountId = 'acc1'
    When method POST
    Then status 404
    And match response.err.message == '#string'
