# ********RoostGPT********

# Test generated by RoostGPT for test products using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /debitcardInfoValidation_post for http method type POST 
# RoostTestHash=332e5b852f
# 
# 

# ********RoostGPT********
Feature: Debit Card Information Validation

  Background:
    * def baseURL = karate.properties['BANKASSIST_CORE_BANKING_SPECIFICATION_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN'] || karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Validate debit card information with valid inputs
    Given path 'debitcardInfoValidation'
    And request
      """
      {
        "customerId": <customerId>,
        "cvv": '<cvv>',
        "debitCardNumber": '<debitCardNumber>',
        "expiryDate": '<expiryDate>',
        "pin": '<pin>'
      }
      """
    When method POST
    Then status 200
    And match response == {}

    Examples:
      | customerId | cvv | debitCardNumber | expiryDate                  | pin  |
      | 1045300    | '123' | '1234456778901690' | '2025-01-01T00:00:00.000+0000' | '1111' |

  Scenario: Validate debit card information with missing authorization
    Given path 'debitcardInfoValidation'
    And request
      """
      {
        "customerId": 1045300,
        "cvv": '123',
        "debitCardNumber": '1234456778901690',
        "expiryDate": '2025-01-01T00:00:00.000+0000',
        "pin": '1111'
      }
      """
    * configure headers = { Accept: 'application/json' }
    When method POST
    Then status 401
    And match response.err.message == '#string'

  Scenario: Validate debit card information with invalid endpoint
    Given path 'invalidEndpoint'
    And request
      """
      {
        "customerId": 1045300,
        "cvv": '123',
        "debitCardNumber": '1234456778901690',
        "expiryDate": '2025-01-01T00:00:00.000+0000',
        "pin": '1111'
      }
      """
    When method POST
    Then status 404
    And match response.err.message == '#string'
