# ********RoostGPT********

# Test generated by RoostGPT for test products using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /deeplink_post for http method type POST 
# RoostTestHash=e18295dfea
# 
# 

# ********RoostGPT********
Feature: Deeplink API Tests

  Background:
    * def baseURL = karate.properties['BANKASSIST_CORE_BANKING_SPECIFICATION_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN'] || karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Test GET /deeplink with valid usecase
    Given path '/deeplink'
    And request { "usecase": <usecase> }
    When method POST
    Then status 200
    And match response == '#[]'
    And match each response[*].usecase == '#string'
    And match each response[*].link == '#string'
    And match each response[*].linkType == '#string'

    Examples:
      | usecase                                      |
      | [ 'addbeneficiary' ]                         |
      | [ 'accountclosurestatus_followup' ]          |
      | [ 'travel_followup' ]                        |
      | [ 'fundtransferstatusinquiry' ]              |
      | [ 'transferfunds' ]                          |

  Scenario: Test GET /deeplink with missing authorization
    Given path '/deeplink'
    And request { "usecase": [ 'addbeneficiary' ] }
    * configure headers = { Accept: 'application/json' }
    When method POST
    Then assert responseStatus != 200
    And match response.err.message == '#string'

  Scenario: Test GET /deeplink with invalid endpoint
    Given path '/invalid-deeplink'
    And request { "usecase": [ 'addbeneficiary' ] }
    When method POST
    Then assert responseStatus != 200
    And match response.err.message == '#string'
