# ********RoostGPT********

# Test generated by RoostGPT for test products using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /DeleteRecurringTransfers_post for http method type POST 
# RoostTestHash=2abad00381
# 
# 

# ********RoostGPT********
Feature: Delete Recurring Transfers API

  Background:
    * def baseURL = karate.properties['BANKASSIST_CORE_BANKING_SPECIFICATION_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Delete recurring transfers with valid inputs
    Given path '/DeleteRecurringTransfers'
    And request { "customerId": <customerId>, "paymentId": '<paymentId>', "updateTransferType": '<updateTransferType>' }
    And header botId = '<botId>'
    And header accountId = '<accountId>'
    When method DELETE
    Then status 200

    Examples:
      | customerId | paymentId         | updateTransferType | botId    | accountId |
      | 1045304    | '744a77644d67e891'| 'all'              | 'bot123' | 'acc456'  |

  Scenario Outline: Unauthorized access
    Given path '/DeleteRecurringTransfers'
    And request { "customerId": <customerId>, "paymentId": '<paymentId>', "updateTransferType": '<updateTransferType>' }
    And header botId = '<botId>'
    And header accountId = '<accountId>'
    And configure headers = { Authorization: 'InvalidToken', Accept: 'application/json' }
    When method DELETE
    Then status 401
    And match response.err.message == '#string'

    Examples:
      | customerId | paymentId         | updateTransferType | botId    | accountId |
      | 1045304    | '744a77644d67e891'| 'all'              | 'bot123' | 'acc456'  |

  Scenario Outline: Not found error
    Given path '/DeleteRecurringTransfers'
    And request { "customerId": <customerId>, "paymentId": '<paymentId>', "updateTransferType": '<updateTransferType>' }
    And header botId = '<botId>'
    And header accountId = '<accountId>'
    When method DELETE
    Then status 404
    And match response.err.message == '#string'

    Examples:
      | customerId | paymentId         | updateTransferType | botId    | accountId |
      | 9999999    | 'invalidPaymentId'| 'all'              | 'bot123' | 'acc456'  |
