# ********RoostGPT********

# Test generated by RoostGPT for test products using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /DeleteScheduleTransfers_post for http method type POST 
# RoostTestHash=47355f872f
# 
# 

# ********RoostGPT********
Feature: Delete Scheduled Transfers API Tests

  Background:
    * def baseURL = karate.properties['BANKASSIST_CORE_BANKING_SPECIFICATION_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers =
      """
      {
        Authorization: '#(authToken)',
        Accept: 'application/json'
      }
      """

  Scenario Outline: Delete scheduled transfer with valid inputs
    Given path '/DeleteScheduleTransfers'
    And request
      """
      { 
        "customerId": <customerId>,
        "paymentId": <paymentId>,
        "updateTransferType": <updateTransferType>
      }
      """
    And header botId = <botId>
    And header accountId = <accountId>
    When method DELETE
    Then status 200

    Examples:
      | read('DeleteScheduleTransfers_post.csv') |

  Scenario Outline: Unauthorized access to delete scheduled transfer
    Given path '/DeleteScheduleTransfers'
    And request
      """
      { 
        "customerId": <customerId>,
        "paymentId": <paymentId>,
        "updateTransferType": <updateTransferType>
      }
      """
    And header botId = <botId>
    And header accountId = <accountId>
    * configure headers =
      """
      {
        Authorization: 'InvalidToken',
        Accept: 'application/json'
      }
      """
    When method DELETE
    Then status 401
    And match response.err.message == '#string'

    Examples:
      | customerId | paymentId          | updateTransferType | botId  | accountId |
      |    1045300 | '97087c6c24788b1d' | 'all'              | 'bot1' | 'acc123'  |

  Scenario Outline: Delete scheduled transfer not found
    Given path '/DeleteScheduleTransfers'
    And request
      """
      { 
        "customerId": <customerId>,
        "paymentId": <paymentId>,
        "updateTransferType": <updateTransferType>
      }
      """
    And header botId = <botId>
    And header accountId = <accountId>
    When method DELETE
    Then status 404
    And match response.err.message == '#string'

    Examples:
      | customerId | paymentId       | updateTransferType | botId  | accountId |
      |    1045300 | 'nonexistentId' | 'all'              | 'bot1' | 'acc123'  |
