# ********RoostGPT********

# Test generated by RoostGPT for test products using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /deposit_post for http method type POST 
# RoostTestHash=70db6d5eac
# 
# 

# ********RoostGPT********
Feature: Deposit API Tests

  Background:
    * def baseURL = karate.properties['BANKASSIST_CORE_BANKING_SPECIFICATION_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Test Deposit API with valid inputs
    Given path '/deposit'
    And request
      """
      { 
        "customerId": <customerId>,
        "sourceAccountId": <sourceAccountId>,
        "amount": <amount>,
        "currency": <currency>,
        "image": {
          "frontImage": <frontImage>,
          "backImage": <backImage>
        }
      }
      """
    And header botId = <botId>
    And header accountId = <accountId>
    When method POST
    Then status 200
    And match response == {}

    Examples:
      | read('deposit_post.csv') |

  Scenario: Test Deposit API with missing Authorization header
    Given path '/deposit'
    And request
      """
      { 
        "customerId": 1045300,
        "sourceAccountId": '1042345',
        "amount": '1042222',
        "currency": 'USD',
        "image": {
          "frontImage": 'https://google.com',
          "backImage": 'https://google.com'
        }
      }
      """
    And header botId = 'bot123'
    And header accountId = 'acc123'
    * configure headers = { Accept: 'application/json' }
    When method POST
    Then status 401
    And match response.err.message == '#string'

  Scenario: Test Deposit API with invalid accountId
    Given path '/deposit'
    And request
      """
      { 
        "customerId": 1045300,
        "sourceAccountId": '1042345',
        "amount": '1042222',
        "currency": 'USD',
        "image": {
          "frontImage": 'https://google.com',
          "backImage": 'https://google.com'
        }
      }
      """
    And header botId = 'bot123'
    And header accountId = 'invalid_acc'
    When method POST
    Then status 404
    And match response.err.message == '#string'
