# ********RoostGPT********

# Test generated by RoostGPT for test products using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /disputeTransaction_post for http method type POST 
# RoostTestHash=a16706fdab
# 
# 

# ********RoostGPT********
Feature: Dispute Transaction API Tests

  Background:
    * def baseURL = karate.properties['BANKASSIST_CORE_BANKING_SPECIFICATION_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Dispute Transaction with Valid Inputs
    Given path 'disputeTransaction'
    And request { "customerId": <customerId>, "emailId": '<emailId>', "transactionsData": <transactionsData> }
    And header botId = '<botId>'
    And header accountId = '<accountId>'
    And header koreUserId = '<koreUserId>'
    When method POST
    Then status 200

    Examples:
      | customerId | emailId          | transactionsData                                                                                         | botId  | accountId | koreUserId |
      | 1045300    | 'John@yahoo.com' | [{ "transactionId": 12345, "reasonCode": 'UIDENTF-CHRG' }]                                               | 'bot1' | 'acc123'  | 'user123'  |
      | 1045300    | 'John@yahoo.com' | [{ "transactionId": 12345, "reasonCode": 'CHRG-AMNT-MORE' }, { "transactionId": 67890, "reasonCode": 'CHRG-MULTPLE-TIME' }] | 'bot2' | 'acc456'  | 'user456'  |

  Scenario: Dispute Transaction with Missing Authorization
    Given path 'disputeTransaction'
    And request { "customerId": 1045300, "emailId": 'John@yahoo.com', "transactionsData": [{ "transactionId": 12345, "reasonCode": 'UIDENTF-CHRG' }] }
    And header botId = 'bot1'
    And header accountId = 'acc123'
    And header koreUserId = 'user123'
    * configure headers = { Accept: 'application/json' }
    When method POST
    Then status 401
    And match response.err.message == '#string'

  Scenario: Dispute Transaction with Invalid Endpoint
    Given path 'invalidEndpoint'
    And request { "customerId": 1045300, "emailId": 'John@yahoo.com', "transactionsData": [{ "transactionId": 12345, "reasonCode": 'UIDENTF-CHRG' }] }
    And header botId = 'bot1'
    And header accountId = 'acc123'
    And header koreUserId = 'user123'
    When method POST
    Then status 404
    And match response.err.message == '#string'
