# ********RoostGPT********

# Test generated by RoostGPT for test products using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /GetAccountInfo_post for http method type POST 
# RoostTestHash=8a95fbc531
# 
# 

# ********RoostGPT********
Feature: Get Account Information API Tests

  Background:
    * def baseURL = karate.properties['BANKASSIST_CORE_BANKING_SPECIFICATION_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN'] || karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Validate successful retrieval of account information
    Given path '/GetAccountInfo'
    And request { "customerId": <customerId> }
    And header botId = '<botId>'
    And header accountId = '<accountId>'
    When method post
    Then status 200
    And match response.customerId == <customerId>
    And match response.accounts == '#[]'
    And match each response.accounts[*].customerId == <customerId>
    And match each response.accounts[*].accountName == '#string'
    And match each response.accounts[*].accountNickname == '#string'
    And match each response.accounts[*].accountNumber == '#string'
    And match each response.accounts[*].accountType == '#string'
    And match each response.accounts[*].activatedDate == '#string'
    And match each response.accounts[*].availableBalance == '#number'
    And match each response.accounts[*].availableCash == '##number'
    And match each response.accounts[*].availableCashLimit == '##number'
    And match each response.accounts[*].availableCredit == '##number'
    And match each response.accounts[*].bankName == '##string'
    And match each response.accounts[*].branchName == '##string'
    And match each response.accounts[*].cardName == '##string'
    And match each response.accounts[*].cardNumber == '##string'
    And match each response.accounts[*].cardStatus == '##string'
    And match each response.accounts[*].cardType == '##string'
    And match each response.accounts[*].creditLimit == '##number'
    And match each response.accounts[*].currency == '#string'
    And match each response.accounts[*].currentBalance == '#number'
    And match each response.accounts[*].deactivatedDate == '##string'
    And match each response.accounts[*].dueAmount == '##number'
    And match each response.accounts[*].dueDate == '##string'
    And match each response.accounts[*].earlyWithdrawalPenalty == '##number'
    And match each response.accounts[*].email == '##string'
    And match each response.accounts[*].expiryDate == '##string'
    And match each response.accounts[*].expDate == '##string'
    And match each response.accounts[*].fdType == '##string'
    And match each response.accounts[*].image == '##string'
    And match each response.accounts[*].interestRate == '##number'
    And match each response.accounts[*].internalTransferFromEnabled == '##boolean'
    And match each response.accounts[*].internalTransferToEnabled == '##boolean'
    And match each response.accounts[*].isPrimaryMobile == '##boolean'
    And match each response.accounts[*].isAlternateMobileNumber == '##boolean'
    And match each response.accounts[*].isStatement == '##boolean'
    And match each response.accounts[*].lastDrawDate == '##string'
    And match each response.accounts[*].loanMaturityDate == '##string'
    And match each response.accounts[*].loanOriginationDate == '##string'
    And match each response.accounts[*].location == '##string'
    And match each response.accounts[*].lastUpdated == '#string'
    And match each response.accounts[*].maxTransactionLimit == '##string'
    And match each response.accounts[*].maturityDate == '##string'
    And match each response.accounts[*].minimumPaymentDue == '##string'
    And match each response.accounts[*].minimumBalance == '##string'
    And match each response.accounts[*].monthlyPayment == '##number'
    And match each response.accounts[*].openingBalance == '##number'
    And match each response.accounts[*].originalLoanAmount == '##number'
    And match each response.accounts[*].P2PLimit == '##number'
    And match each response.accounts[*].p2pEnabled == '##number'
    And match each response.accounts[*].paybillEnabled == '##boolean'
    And match each response.accounts[*].payoffAmount == '##number'
    And match each response.accounts[*].personalBankerName == '##string'
    And match each response.accounts[*].personalBankerContact.email == '##string'
    And match each response.accounts[*].personalBankerContact.mobileNumber == '##string'
    And match each response.accounts[*].phone == '##number'
    And match each response.accounts[*].postedBalance == '##number'
    And match each response.accounts[*].principalBalance == '##string'
    And match each response.accounts[*].productCode == '##string'
    And match each response.accounts[*].productName == '##string'
    And match each response.accounts[*].propertyAddress == '##string'
    And match each response.accounts[*].rewardPoints == '##string'
    And match each response.accounts[*].routingNumber == '##string'
    And match each response.accounts[*].statementDate == '##string'
    And match each response.accounts[*].status == '#string'
    And match each response.accounts[*].swiftCode == '##string'
    And match each response.accounts[*].totalBalance == '##number'
    And match each response.accounts[*].unbilledAmount == '##number'
    And match each response.accounts[*].userId == '##string'
    And match each response.accounts[*].valueAtMaturity == '##number'
    And match each response.accounts[*].holdAmount == '##number'
    And match each response.accounts[*].unclearFundsAmount == '##number'
    And match each response.accounts[*].averageMonthlyBalance == '##number'
    And match each response.accounts[*].netWithdrawableBalance == '##number'
    And match each response.accounts[*].totalTenure == '##string'
    And match each response.accounts[*].remainingTenure == '##string'
    And match each response.accounts[*].debitAccountNumber == '##string'
    And match each response.accounts[*].lateFee == '##number'
    And match each response.accounts[*].bounceCharge == '##number'
    And match each response.accounts[*].totalCharges == '##number'
    And match each response.accounts[*].overDueAmount == '##number'
    And match each response.accounts[*].id == '##string'

    Examples:
      | customerId | botId   | accountId |
      | 1045300    | 'bot123'| 'acc123'  |

  Scenario: Validate unauthorized access
    Given path '/GetAccountInfo'
    And request { "customerId": 1045300 }
    And header botId = 'bot123'
    And header accountId = 'acc123'
    And configure headers = { Accept: 'application/json' }
    When method post
    Then status 401
    And match response.err.message == '#string'

  Scenario: Validate not found error
    Given path '/GetAccountInfo'
    And request { "customerId": 9999999 }
    And header botId = 'bot123'
    And header accountId = 'acc123'
    When method post
    Then status 404
    And match response.err.message == '#string'
