# ********RoostGPT********

# Test generated by RoostGPT for test products using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /GetCustomerInfo_post for http method type POST 
# RoostTestHash=88810bf424
# 
# 

# ********RoostGPT********
Feature: Get Customer Information API Tests

  Background:
    * def baseURL = karate.properties['BANKASSIST_CORE_BANKING_SPECIFICATION_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Test GetCustomerInfo with valid inputs
    Given path 'GetCustomerInfo'
    And request { "customerId": <customerId> }
    And header botId = '<botId>'
    And header accountId = '<accountId>'
    When method GET
    Then status 200
    And match response == '#object'
    And match response.alternatePhoneNumber == '##number'
    And match response.customerId == '##string'
    And match response.email == '##string'
    And match response.identificationNumber == '##number'
    And match response.identificationType == '##string'
    And match response.image == '##string'
    And match response.isAlternateMobileNumber == '##boolean'
    And match response.isPrimaryMobileNumber == '##boolean'
    And match response.location == '##string'
    And match response.name == '##string'
    And match response.firstName == '##string'
    And match response.lastName == '##string'
    And match response.personalBanker.name == '##string'
    And match response.personalBanker.email == '##string'
    And match response.personalBanker.mobileNumber == '##string'
    And match response.phone == '##number'
    And match response.securityQuestions == '#[]'
    And match each response.securityQuestions[*].Q == '##string'
    And match each response.securityQuestions[*].A == '##string'
    And match response.segmentId == '##number'
    And match response.userId == '##string'
    And match response.id == '##string'

    Examples:
      | customerId | botId   | accountId |
      | 1045300    | 'bot123' | 'acc456'  |

  Scenario: Test GetCustomerInfo with missing Authorization
    Given path 'GetCustomerInfo'
    And request { "customerId": 1045300 }
    And header botId = 'bot123'
    And header accountId = 'acc456'
    * configure headers = { Accept: 'application/json' }
    When method GET
    Then status 401
    And match response.err.message == '##string'

  Scenario: Test GetCustomerInfo with invalid customerId
    Given path 'GetCustomerInfo'
    And request { "customerId": 9999999 }
    And header botId = 'bot123'
    And header accountId = 'acc456'
    When method GET
    Then status 404
    And match response.err.message == '##string'
