# ********RoostGPT********

# Test generated by RoostGPT for test products using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /GetRecurringTransfers_post for http method type POST 
# RoostTestHash=7e03af5a84
# 
# 

# ********RoostGPT********
Feature: Get Recurring Transfers API Tests

  Background:
    * def baseURL = karate.properties['BANKASSIST_CORE_BANKING_SPECIFICATION_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Validate successful retrieval of recurring transfers
    Given path '/GetRecurringTransfers'
    And request { "customerId": <customerId>, "status": '<status>' }
    And header botId = '<botId>'
    And header accountId = '<accountId>'
    When method GET
    Then status 200
    And match response == '#[]'
    And match each response[*].Type == '#string'
    And match each response[*].CustomerId == '#number'
    And match each response[*].Amount == '#number'
    And match each response[*].SourceAccountNumber == '#string'
    And match each response[*].TargetAccountNumber == '#string'
    And match each response[*].Currency == '#string'
    And match each response[*].Status == '#string'
    And match each response[*].ScheduledDate == '#number'
    And match each response[*].recurringOptions.amountType == '#string'
    And match each response[*].recurringOptions.frequency.iterate == '#string'
    And match each response[*].recurringOptions.frequency.duration.numberOfTransfers == '##number'
    And match each response[*].id == '#string'

    Examples:
      | customerId | status   | botId   | accountId |
      | 1045304    | 'Pending' | 'bot123' | 'acc123'  |

  Scenario: Validate authorization failure
    Given path '/GetRecurringTransfers'
    And request { "customerId": 1045304, "status": 'Pending' }
    And header botId = 'bot123'
    And header accountId = 'acc123'
    And configure headers = { Authorization: 'InvalidToken', Accept: 'application/json' }
    When method GET
    Then status 401
    And match response.err.message == '#string'

  Scenario: Validate not found error
    Given path '/GetRecurringTransfers'
    And request { "customerId": 9999999, "status": 'NonExistent' }
    And header botId = 'bot123'
    And header accountId = 'acc123'
    When method GET
    Then status 404
    And match response.err.message == '#string'
