# ********RoostGPT********

# Test generated by RoostGPT for test products using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /GetScheduleTransfers_post for http method type POST 
# RoostTestHash=7b4d2d87f9
# 
# 

# ********RoostGPT********
Feature: Get Schedule Transfers API Tests

  Background:
    * def baseURL = karate.properties['BANKASSIST_CORE_BANKING_SPECIFICATION_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN'] || karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Validate Get Schedule Transfers with valid inputs
    Given path '/GetScheduleTransfers'
    And request { "customerId": <customerId>, "status": '<status>' }
    And header botId = '<botId>'
    And header accountId = '<accountId>'
    When method GET
    Then status 200
    And match response == '#[]'
    And match each response[*].Type == '#string'
    And match each response[*].CustomerId == '#number'
    And match each response[*].Amount == '#number'
    And match each response[*].SourceAccountNumber == '#string'
    And match each response[*].TargetAccountNumber == '#string'
    And match each response[*].DueDate == '#string'
    And match each response[*].Currency == '#string'
    And match each response[*].Status == '#string'
    And match each response[*].ScheduledDate == '#number'
    And match each response[*].NextScheduleDate == '##number'
    And match each response[*].id == '#string'

    Examples:
      | customerId | status   | botId   | accountId |
      | 1045300    | 'Pending'| 'bot123'| 'acc123'  |

  Scenario: Validate Get Schedule Transfers with missing Authorization
    Given path '/GetScheduleTransfers'
    And request { "customerId": 1045300, "status": 'Pending' }
    And header botId = 'bot123'
    And header accountId = 'acc123'
    * configure headers = { Accept: 'application/json' }
    When method GET
    Then status 401
    And match response.err.message == '#string'

  Scenario: Validate Get Schedule Transfers with invalid endpoint
    Given path '/InvalidEndpoint'
    And request { "customerId": 1045300, "status": 'Pending' }
    And header botId = 'bot123'
    And header accountId = 'acc123'
    When method GET
    Then status 404
    And match response.err.message == '#string'
