# ********RoostGPT********

# Test generated by RoostGPT for test products using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /GetTransactions_post for http method type POST 
# RoostTestHash=207beafabe
# 
# 

# ********RoostGPT********
Feature: Get Transactions API

  Background:
    * def baseURL = karate.properties['BANKASSIST_CORE_BANKING_SPECIFICATION_BASE_URL'] || karate.properties['API_HOST']
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN'] || karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }
    * url baseURL

  Scenario Outline: Fetch transactions with valid input
    Given path 'GetTransactions'
    And request
      """
      {
        "customerId": <customerId>,
        "accountNumber": <accountNumber>,
        "category": <category>,
        "startDate": <startDate>,
        "endDate": <endDate>,
        "status": <status>,
        "transactionAmount": <transactionAmount>
      }
      """
    When method POST
    Then status 200
    And match response == '#[]'
    And match each response[*].customerId == '#number'
    And match each response[*].transactionId == '#number'
    And match each response[*].accountNumber == '#string'
    And match each response[*].timestamp == '#number'
    And match each response[*].amount == '#number'
    And match each response[*].currency == '#string'
    And match each response[*].debitOrCredit == '#string'
    And match each response[*].description == '#string'
    And match each response[*].paymentMode == '##string'
    And match each response[*].DBANames == '##string'
    And match each response[*].status == '#string'
    And match each response[*].transactionType == '##string'
    And match each response[*].MCCCode == '##string'
    And match each response[*].name == '##string'
    And match each response[*].address == '##string'
    And match each response[*].street == '##string'
    And match each response[*].city == '##string'
    And match each response[*].state == '##string'
    And match each response[*].zip == '##string'
    And match each response[*].country == '##string'
    And match each response[*].phoneNumber == '##number'
    And match each response[*].metaInfo == '##[]'

    Examples:
      | customerId | accountNumber      | category                                                                                                                                 | startDate               | endDate                 | status  | transactionAmount                                                                 |
      | 1045300    | ['1045301']        | [{'codeType': 'MCC', 'value': [['5811', '5814']], 'source': 'Internal'}]                                                                | '2021-04-01T00:00:00.000+0000' | '2021-04-30T00:00:00.000+0000' | 'Posted' | {'amount': {'gt': 1000}, 'currency': 'USD'}                                        |
      | 1045300    | ['1045302']        | [{'codeType': 'TransactionCode', 'value': [['1234', '5678']], 'source': 'Internal'}]                                                    | '2021-05-01T00:00:00.000+0000' | '2021-05-31T00:00:00.000+0000' | 'Pending' | {'amount': {'lt': 500}, 'currency': 'EUR'}                                         |
      | 1045300    | ['1045303']        | [{'codeType': 'MCC', 'value': [['1111', '2222']], 'source': 'External'}]                                                                | '2021-06-01T00:00:00.000+0000' | '2021-06-30T00:00:00.000+0000' | 'Completed' | {'amount': {'gt': 2000}, 'currency': 'GBP'}                                        |
