# ********RoostGPT********

# Test generated by RoostGPT for test products using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /locateProfile_post for http method type POST 
# RoostTestHash=2b60fcac41
# 
# 

# ********RoostGPT********
Feature: Locate Profile API Tests

  Background:
    * def baseURL = karate.properties['BANKASSIST_CORE_BANKING_SPECIFICATION_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN'] || karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Test Locate Profile with valid inputs
    Given path '/locateProfile'
    And request
      """
      {
        "customerId": "<customerId>",
        "ssNumber": "<ssNumber>",
        "ssnShort": "<ssnShort>",
        "accountNumber": "<accountNumber>"
      }
      """
    When method POST
    Then status 200
    And match response.accountNumber == '#string'
    And match response.cardDetails.cardNumber == '#string'
    And match response.cardDetails.expiryDate == '#string'
    And match response.cardDetails.cvv == '#string'
    And match response.cardDetails.pin == '#string'
    And match response.personalQuestions.DOB == '#string'
    And match response.personalQuestions.SSN == '#number'
    And match response.personalQuestions.SecretPassword == '#string'
    And match response.personalQuestions.LDAmount == '#number'
    And match response.personalQuestions.AccNumber == '#string'
    And match response.ssNumber == '#number'
    And match response.ssnShort == '#number'
    And match response.alternatePhoneNumber == '#number'
    And match response.customerId == '#string'
    And match response.email == '#string'
    And match response.identificationNumber == '#string'
    And match response.identificationType == '#string'
    And match response.image == '#string'
    And match response.isAlternateMobileNumber == '#boolean'
    And match response.isPrimaryMobileNumber == '#boolean'
    And match response.location == '#string'
    And match response.name == '#string'
    And match response.personalBanker.name == '#string'
    And match response.personalBanker.email == '#string'
    And match response.personalBanker.mobileNumber == '#string'
    And match response.phone == '#number'
    And match response.securityQuestions == '#array'
    And match each response.securityQuestions[*] == '#string'
    And match response.segmentId == '#number'
    And match response.userId == '#string'

    Examples:
      | customerId | ssNumber | ssnShort | accountNumber |
      | '1045300'  | 104531234 | 1234     | '1042345'     |

  Scenario: Test Locate Profile with missing authorization
    Given path '/locateProfile'
    And request
      """
      {
        "customerId": "1045300",
        "ssNumber": 104531234,
        "ssnShort": 1234,
        "accountNumber": "1042345"
      }
      """
    And configure headers = { Accept: 'application/json' }
    When method POST
    Then status 401
    And match response.err.message == '#string'

  Scenario: Test Locate Profile with invalid endpoint
    Given path '/locateProfileInvalid'
    And request
      """
      {
        "customerId": "1045300",
        "ssNumber": 104531234,
        "ssnShort": 1234,
        "accountNumber": "1042345"
      }
      """
    When method POST
    Then status 404
    And match response.err.message == '#string'
