# ********RoostGPT********

# Test generated by RoostGPT for test products using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /personalInfoValidation_post for http method type POST 
# RoostTestHash=be461d4c4c
# 
# 

# ********RoostGPT********
Feature: Personal Info Validation API Tests

  Background:
    * def baseURL = karate.properties['BANKASSIST_CORE_BANKING_SPECIFICATION_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN'] || karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Validate personal info with various combinations of request body
    Given path '/personalInfoValidation'
    And request
      """
      {
        "customerId": <customerId>,
        "dob": <dob>,
        "ssn": <ssn>,
        "secrectPassword": <secrectPassword>,
        "AccNumber": <AccNumber>,
        "lastDepositAmt": <lastDepositAmt>
      }
      """
    When method POST
    Then status 200
    And match response == {}

    Examples:
      | customerId | dob                      | ssn      | secrectPassword | AccNumber | lastDepositAmt |
      | 1045300    | '1999-05-05T00:00:00.000+0000' | null     | null            | null      | null           |
      | 1045300    | null                     | 104531234 | null            | null      | null           |
      | 1045300    | null                     | null      | 'Sam'           | null      | null           |
      | 1045300    | null                     | null      | null            | '1042345' | null           |
      | 1045300    | null                     | null      | null            | null      | 500            |

  Scenario: Authorization failure
    Given path '/personalInfoValidation'
    And request
      """
      {
        "customerId": 1045300,
        "dob": '1999-05-05T00:00:00.000+0000'
      }
      """
    * configure headers = { Accept: 'application/json' } # No Authorization header
    When method POST
    Then status 401
    And match response.err.message == '#string'

  Scenario: Resource not found
    Given path '/personalInfoValidation'
    And request
      """
      {
        "customerId": 9999999,
        "dob": '1999-05-05T00:00:00.000+0000'
      }
      """
    When method POST
    Then status 404
    And match response.err.message == '#string'
