# ********RoostGPT********

# Test generated by RoostGPT for test products using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /resetPassword_post for http method type POST 
# RoostTestHash=79c3f016d8
# 
# 

# ********RoostGPT********
Feature: Reset Password API Tests

  Background:
    * def baseURL = karate.properties['BANKASSIST_CORE_BANKING_SPECIFICATION_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN'] || karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Test Reset Password with Valid Inputs
    Given path '/resetPassword'
    And request { "username": '<username>', "password": '<password>' }
    When method POST
    Then status 200
    And match response == {}

    Examples:
      | username | password |
      | 'John'   | '1111'   |
      | 'Jane'   | '2222'   |

  Scenario: Test Reset Password with Missing Authorization
    Given path '/resetPassword'
    And request { "username": 'John', "password": '1111' }
    * configure headers = { Accept: 'application/json' }
    When method POST
    Then assert responseStatus != 200
    And match response.err.message == '#string'

  Scenario: Test Reset Password with Invalid Endpoint
    Given path '/invalidEndpoint'
    And request { "username": 'John', "password": '1111' }
    When method POST
    Then assert responseStatus != 200
    And match response.err.message == '#string'

  Scenario: Test Reset Password with Invalid Method
    Given path '/resetPassword'
    And request { "username": 'John', "password": '1111' }
    When method GET
    Then assert responseStatus != 200
    And match response.err.message == '#string'

  Scenario: Test Reset Password with Missing Fields
    Given path '/resetPassword'
    And request { "username": 'John' }
    When method POST
    Then assert responseStatus != 200
    And match response.err.message == '#string'

  Scenario: Test Reset Password with Unauthorized Access
    Given path '/resetPassword'
    And request { "username": 'John', "password": '1111' }
    * configure headers = { Authorization: 'Bearer invalid_token', Accept: 'application/json' }
    When method POST
    Then status 401
    And match response.err.message == '#string'

  Scenario: Test Reset Password Not Found
    Given path '/resetPassword'
    And request { "username": 'NonExistentUser', "password": '1111' }
    When method POST
    Then status 404
    And match response.err.message == '#string'
