# ********RoostGPT********

# Test generated by RoostGPT for test products using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /sendsecuremessage_post for http method type POST 
# RoostTestHash=3b0ac86130
# 
# 

# ********RoostGPT********
Feature: Secure Message API Tests

  Background:
    * def baseURL = karate.properties['BANKASSIST_CORE_BANKING_SPECIFICATION_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN'] || karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Test sending secure message with valid payload
    Given path 'sendsecuremessage'
    And request
      """
      {
        "authType": "<authType>",
        "firstName": "<firstName>",
        "lastName": "<lastName>",
        "email": "<email>",
        "phoneNumber": <phoneNumber>,
        "topic": "<topic>",
        "message": "<message>",
        "availableTime": "<availableTime>",
        "chatHistory": "<chatHistory>",
        "cif": <cif>
      }
      """
    When method POST
    Then status 200
    And match response == {}

    Examples:
      | authType   | firstName | lastName | email            | phoneNumber | topic                        | message                              | availableTime | chatHistory                              | cif    |
      | 'Authorized' | 'James'   | 'William' | 'James@gmail.com' | 9787643445  | 'Routing and Account Number' | 'Unable to find my routing number.' | 'nighttime'   | 'html formatted message sent as string' | 1045310 |

  Scenario: Test sending secure message with missing authorization
    Given path 'sendsecuremessage'
    * configure headers = { Accept: 'application/json' }
    And request
      """
      {
        "authType": "Authorized",
        "firstName": "James",
        "lastName": "William",
        "email": "James@gmail.com",
        "phoneNumber": 9787643445,
        "topic": "Routing and Account Number",
        "message": "Unable to find my routing number.",
        "availableTime": "nighttime",
        "chatHistory": "html formatted message sent as string",
        "cif": 1045310
      }
      """
    When method POST
    Then assert responseStatus != 200
    And match response.err.message == '#string'

  Scenario: Test sending secure message with invalid endpoint
    Given path 'invalidendpoint'
    And request
      """
      {
        "authType": "Authorized",
        "firstName": "James",
        "lastName": "William",
        "email": "James@gmail.com",
        "phoneNumber": 9787643445,
        "topic": "Routing and Account Number",
        "message": "Unable to find my routing number.",
        "availableTime": "nighttime",
        "chatHistory": "html formatted message sent as string",
        "cif": 1045310
      }
      """
    When method POST
    Then assert responseStatus != 200
    And match response.err.message == '#string'
