# ********RoostGPT********

# Test generated by RoostGPT for test products using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /TransferFunds_post for http method type POST 
# RoostTestHash=289ed66c26
# 
# 

# ********RoostGPT********
Feature: Transfer Funds API Tests

  Background:
    * def baseURL = karate.properties['BANKASSIST_CORE_BANKING_SPECIFICATION_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN'] || karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Transfer funds with valid data
    Given path '/TransferFunds'
    And request
      """
      { 
        "customerId": <customerId>,
        "amount": <amount>,
        "currency": <currency>,
        "sourceAccountId": <sourceAccountId>,
        "targetAccountId": <targetAccountId>,
        "date": <date>,
        "description": <description>,
        "TransactionType": <TransactionType>,
        "PaymentType": <PaymentType>
      }
      """
    And header botId = <botId>
    And header accountId = <accountId>
    When method POST
    Then status 200

    Examples:
      | read('TransferFunds_post.csv') |

  Scenario: Unauthorized transfer attempt
    Given path '/TransferFunds'
    And request
      """
      { 
        "customerId": 1045300,
        "amount": 3,
        "currency": 'USD',
        "sourceAccountId": '1042345',
        "targetAccountId": '1042222',
        "date": '03-15-2021',
        "description": 'Internal Transfer',
        "TransactionType": '1063',
        "PaymentType": 'Minimum Payment'
      }
      """
    And header botId = 'bot1'
    And header accountId = 'acc1'
    And configure headers = { Accept: 'application/json' }
    When method POST
    Then status 401
    And match response.err.message == '#string'

  Scenario: Transfer to non-existent account
    Given path '/TransferFunds'
    And request
      """
      { 
        "customerId": 1045300,
        "amount": 3,
        "currency": 'USD',
        "sourceAccountId": '1042345',
        "targetAccountId": '9999999',
        "date": '03-15-2021',
        "description": 'Internal Transfer',
        "TransactionType": '1063',
        "PaymentType": 'Minimum Payment'
      }
      """
    And header botId = 'bot1'
    And header accountId = 'acc1'
    When method POST
    Then status 404
    And match response.err.message == '#string'
