# ********RoostGPT********

# Test generated by RoostGPT for test products using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /UpdateAccountInfo_put for http method type PUT 
# RoostTestHash=adb57fbf1b
# 
# 

# ********RoostGPT********
Feature: Update Account Information API Tests

  Background:
    * def baseURL = karate.properties['BANKASSIST_CORE_BANKING_SPECIFICATION_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN'] || karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Update account information with valid data
    Given path '/UpdateAccountInfo'
    And request
      """
      {
        "accountNumber": "<accountNumber>",
        "customerId": <customerId>,
        "email": "<email>",
        "alternatePhoneNumber": <alternatePhoneNumber>,
        "isAlternateMobileNumber": <isAlternateMobileNumber>,
        "phone": <phone>,
        "isPrimaryMobileNumber": <isPrimaryMobileNumber>,
        "location": "<location>",
        "isStatement": <isStatement>
      }
      """
    And header botId = '<botId>'
    And header accountId = '<accountId>'
    And header koreUserId = '<koreUserId>'
    And header X-Auth-token = '<XAuthToken>'
    And header X-CORRELATION-ID = <XCorrelationId>
    When method PUT
    Then status 200
    And match response == {}

    Examples:
      | accountNumber | customerId | email            | alternatePhoneNumber | isAlternateMobileNumber | phone | isPrimaryMobileNumber | location | isStatement | botId | accountId | koreUserId | XAuthToken | XCorrelationId |
      | '1042345'     | 1045300    | 'John@gmail.com' | 1234567890           | true                   | 9876543210 | false                | 'NY'    | true        | 'bot123' | 'acc123' | 'user123' | 'token123' | 123456 |

  Scenario: Authorization failure
    Given path '/UpdateAccountInfo'
    And request
      """
      {
        "accountNumber": "1042345",
        "customerId": 1045300
      }
      """
    And header botId = 'bot123'
    And header accountId = 'acc123'
    And header koreUserId = 'user123'
    And header X-Auth-token = 'token123'
    And header X-CORRELATION-ID = 123456
    * configure headers = { Authorization: 'Bearer invalid_token', Accept: 'application/json' }
    When method PUT
    Then status 401
    And match response.err.message == '#string'

  Scenario: Account not found
    Given path '/UpdateAccountInfo'
    And request
      """
      {
        "accountNumber": "nonexistent",
        "customerId": 999999
      }
      """
    And header botId = 'bot123'
    And header accountId = 'acc123'
    And header koreUserId = 'user123'
    And header X-Auth-token = 'token123'
    And header X-CORRELATION-ID = 123456
    When method PUT
    Then status 404
    And match response.err.message == '#string'
