# ********RoostGPT********

# Test generated by RoostGPT for test products using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /UpdateRecurringTransfers_put for http method type PUT 
# RoostTestHash=d94103a8c3
# 
# 

# ********RoostGPT********
Feature: Update Recurring Transfers API Tests

  Background:
    * def baseURL = karate.properties['BANKASSIST_CORE_BANKING_SPECIFICATION_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN'] || karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Update Recurring Transfers with Valid Inputs
    Given path '/UpdateRecurringTransfers'
    And request
      """
      { 
        "customerId": <customerId>,
        "paymentId": <paymentId>,
        "amount": <amount>,
        "scheduledDate": <scheduledDate>,
        "sourceAccountId": <sourceAccountId>,
        "targetAccountId": <targetAccountId>,
        "recurringOptions": <recurringOptions>
      }
      """
    And header botId = <botId>
    And header accountId = <accountId>
    When method POST
    Then status 200
    And match response == {}

    Examples:
      | read('UpdateRecurringTransfers_put.csv') |

  Scenario: Update Recurring Transfers with Missing Authorization
    Given path '/UpdateRecurringTransfers'
    And request
      """
      { 
        "customerId": 1045304,
        "paymentId": '744a77644d67e891'
      }
      """
    And header botId = 'bot123'
    And header accountId = 'acc123'
    When method POST
    Then assert responseStatus != 200
    And match response.err.message == '#string'

  Scenario: Update Recurring Transfers with Invalid Endpoint
    Given path '/InvalidEndpoint'
    And request
      """
      { 
        "customerId": 1045304,
        "paymentId": '744a77644d67e891'
      }
      """
    And header botId = 'bot123'
    And header accountId = 'acc123'
    When method POST
    Then assert responseStatus != 200
    And match response.err.message == '#string'
