# ********RoostGPT********

# Test generated by RoostGPT for test products using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /UpdateCustomerInfo_put for http method type PUT 
# RoostTestHash=89ddb90785
# 
# 

# ********RoostGPT********
Feature: Update Customer Information API Tests

  Background:
    * def baseURL = karate.properties['BANKASSIST_CORE_BANKING_SPECIFICATION_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)' }

  Scenario Outline: Update customer information with valid data
    Given path '/UpdateCustomerInfo'
    And request
      """
      { 
        "customerId": <customerId>,
        "email": <email>,
        "alternatePhoneNumber": <alternatePhoneNumber>,
        "isAlternateMobileNumber": <isAlternateMobileNumber>,
        "phone": <phone>,
        "isPrimaryMobileNumber": <isPrimaryMobileNumber>,
        "location": <location>
      }
      """
    And header botId = <botId>
    And header accountId = <accountId>
    And header X-Auth-token = <xAuthToken>
    And header X-CORRELATION-ID = <xCorrelationId>
    When method PUT
    Then status 200
    And match response == {}

    Examples:
      | read('UpdateCustomerInfo_put.csv') |

  Scenario: Authorization failed
    Given path '/UpdateCustomerInfo'
    And request
      """
      { "customerId": 1045300 }
      """
    And header botId = 'bot123'
    And header accountId = 'acc123'
    And header X-Auth-token = 'token123'
    And header X-CORRELATION-ID = 123456
    * configure headers = { Authorization: 'InvalidToken' }
    When method PUT
    Then status 401
    And match response.err.message == '#string'

  Scenario: Resource not found
    Given path '/UpdateCustomerInfo'
    And request
      """
      { "customerId": 9999999 }
      """
    And header botId = 'bot123'
    And header accountId = 'acc123'
    And header X-Auth-token = 'token123'
    And header X-CORRELATION-ID = 123456
    When method PUT
    Then status 404
    And match response.err.message == '#string'
