# ********RoostGPT********

# Test generated by RoostGPT for test products using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /UpdateScheduleTransfers_put for http method type PUT 
# RoostTestHash=c0505709a3
# 
# 

# ********RoostGPT********
Feature: Update Scheduled Transfers API Tests

  Background:
    * def baseURL = karate.properties['BANKASSIST_CORE_BANKING_SPECIFICATION_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN'] || karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Update scheduled transfers with valid inputs
    Given path '/UpdateScheduleTransfers'
    And request { "paymentId": "<paymentId>", "customerId": <customerId>, "amount": <amount>, "scheduledDate": <scheduledDate>, "sourceAccountId": "<sourceAccountId>", "targetAccountId": "<targetAccountId>" }
    And header botId = '<botId>'
    And header accountId = '<accountId>'
    When method POST
    Then status 200
    And match response == {}

    Examples:
      | paymentId          | customerId | amount | scheduledDate | sourceAccountId | targetAccountId | botId | accountId |
      | '97087c6c24788b1d' | 1045300    | 5      | 1672531199000 | 'source123'     | 'target123'     | 'bot1' | 'account1' |

  Scenario: Authorization failure
    Given path '/UpdateScheduleTransfers'
    And request { "paymentId": "97087c6c24788b1d", "customerId": 1045300, "amount": 5 }
    And header botId = 'bot1'
    And header accountId = 'account1'
    * configure headers = { Authorization: 'Bearer invalid_token', Accept: 'application/json' }
    When method POST
    Then status 401
    And match response.err.message == '#string'

  Scenario: Resource not found
    Given path '/UpdateScheduleTransfers'
    And request { "paymentId": "nonexistent", "customerId": 1045300, "amount": 5 }
    And header botId = 'bot1'
    And header accountId = 'account1'
    When method POST
    Then status 404
    And match response.err.message == '#string'
