# ********RoostGPT********

# Test generated by RoostGPT for test products using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /validatePINRules_post for http method type POST 
# RoostTestHash=f3d6df40ff
# 
# 

# ********RoostGPT********
Feature: Validate PIN Rules API

  Background:
    * def baseURL = karate.properties['BANKASSIST_CORE_BANKING_SPECIFICATION_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN'] || karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Validate PIN with valid input
    Given path 'validatePINRules'
    And request { "sourcePin": "<sourcePin>" }
    When method POST
    Then status 200

    Examples:
      | sourcePin |
      | '1357#'   |
      | '2468#'   |

  Scenario Outline: Validate PIN with missing authorization
    Given path 'validatePINRules'
    And request { "sourcePin": "<sourcePin>" }
    * configure headers = { Accept: 'application/json' }
    When method POST
    Then status 401
    And match response.err.message == '#string'

    Examples:
      | sourcePin |
      | '1357#'   |

  Scenario Outline: Validate PIN with invalid endpoint
    Given path 'invalidEndpoint'
    And request { "sourcePin": "<sourcePin>" }
    When method POST
    Then status 404
    And match response.err.message == '#string'

    Examples:
      | sourcePin |
      | '1357#'   |
