# ********RoostGPT********

# Test generated by RoostGPT for test products using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /validatePIN_post for http method type POST 
# RoostTestHash=ace9690a7f
# 
# 

# ********RoostGPT********
Feature: Validate PIN API Tests

  Background:
    * def baseURL = karate.properties['BANKASSIST_CORE_BANKING_SPECIFICATION_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN'] || karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Validate PIN with valid inputs
    Given path '/validatePIN'
    And request
      """
      {
        "sourcePin": "<sourcePin>",
        "targetPin": "<targetPin>",
        "profileInfo": {
          "customerId": "<customerId>",
          "accountNumber": "<accountNumber>",
          "ssn": "<ssn>"
        }
      }
      """
    When method POST
    Then status 200
    And match response == {}

    Examples:
      | sourcePin | targetPin | customerId | accountNumber | ssn   |
      | '1357#'   | '1357#'   | '12345'    | '1045301'     | '123456' |

  Scenario Outline: Validate PIN with missing authorization
    Given path '/validatePIN'
    And request
      """
      {
        "sourcePin": "<sourcePin>",
        "targetPin": "<targetPin>",
        "profileInfo": {
          "customerId": "<customerId>",
          "accountNumber": "<accountNumber>",
          "ssn": "<ssn>"
        }
      }
      """
    * configure headers = { Accept: 'application/json' }
    When method POST
    Then status 401
    And match response.err.message == '#string'

    Examples:
      | sourcePin | targetPin | customerId | accountNumber | ssn   |
      | '1357#'   | '1357#'   | '12345'    | '1045301'     | '123456' |

  Scenario Outline: Validate PIN with invalid endpoint
    Given path '/invalidEndpoint'
    And request
      """
      {
        "sourcePin": "<sourcePin>",
        "targetPin": "<targetPin>",
        "profileInfo": {
          "customerId": "<customerId>",
          "accountNumber": "<accountNumber>",
          "ssn": "<ssn>"
        }
      }
      """
    When method POST
    Then status 404
    And match response.err.message == '#string'

    Examples:
      | sourcePin | targetPin | customerId | accountNumber | ssn   |
      | '1357#'   | '1357#'   | '12345'    | '1045301'     | '123456' |
