# ********RoostGPT********

# Test generated by RoostGPT for test products using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /validateExistingUser_post for http method type POST 
# RoostTestHash=a752951f52
# 
# 

# ********RoostGPT********
Feature: Validate Existing User API

  Background:
    * def baseURL = karate.properties['BANKASSIST_CORE_BANKING_SPECIFICATION_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN'] || karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Validate existing user with valid and invalid inputs
    Given path '/validateExistingUser'
    And request
      """
      {
        "sourcePin": "<sourcePin>",
        "targetPin": "<targetPin>"
      }
      """
    When method POST
    Then assert responseStatus == <expectedStatus>
    And match response == <expectedResponse>

    Examples:
      | sourcePin                        | targetPin | expectedStatus | expectedResponse                                                                 |
      | '5aa5836c710427cfc7b48d3f58cd5779' | '1357#'   | 200            | {}                                                                               |
      | 'invalidPin'                      | '1357#'   | 401            | { err: { message: '#string' } }                                                  |
      | '5aa5836c710427cfc7b48d3f58cd5779' | 'wrong#'  | 404            | { err: { message: '#string' } }                                                  |

  Scenario: Validate existing user without authorization
    Given path '/validateExistingUser'
    And request
      """
      {
        "sourcePin": "5aa5836c710427cfc7b48d3f58cd5779",
        "targetPin": "1357#"
      }
      """
    And configure headers = { Accept: 'application/json' }
    When method POST
    Then assert responseStatus == 401
    And match response.err.message == '#string'
